# Generated by Django 5.2 on 2025-04-24 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0001_Users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
