# Generated by Django 5.2 on 2025-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0002_Users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Nome'),
        ),
    ]
