# Generated by Django 5.2 on 2025-04-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0003_alter_users_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('birth_date', models.DateField(verbose_name='Data de nascimento')),
                ('city', models.CharField(max_length=150, verbose_name='Cidade')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('is_patient', models.BooleanField(default=False, verbose_name='É paciente renal?')),
                ('password', models.CharField(max_length=50, verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'registro de usuário',
                'verbose_name_plural': 'regitros de usuários',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
