# Generated by Django 5.2 on 2025-04-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0004_register_users_delete_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_users',
            name='password',
            field=models.CharField(max_length=200, verbose_name='Senha'),
        ),
    ]
