# Generated by Django 5.2 on 2025-04-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0005_alter_register_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_users',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Arquivar registro'),
        ),
    ]
