# Generated by Django 5.2 on 2025-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0006_register_users_is_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='register_users',
            options={'verbose_name': 'registro de usuário', 'verbose_name_plural': 'registros de usuários'},
        ),
        migrations.AddField(
            model_name='register_users',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
