# Generated by Django 5.2 on 2025-05-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0008_recent_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('age', models.IntegerField(verbose_name='Idade')),
                ('city', models.CharField(max_length=150, verbose_name='Cidade')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonial/', verbose_name='Imagem')),
                ('testimonial', models.TextField(max_length=250, verbose_name='Seu depoimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Depoimento',
                'verbose_name_plural': 'Depoimentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
