# Generated by Django 5.2 on 2025-05-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0009_testimonials'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='history/', verbose_name='Imagem')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'sobre',
                'verbose_name_plural': 'sobre',
            },
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='testimonial',
            field=models.TextField(verbose_name='Seu depoimento'),
        ),
    ]
