# Generated by Django 5.2 on 2025-05-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0010_history_alter_testimonials_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('file', models.FileField(upload_to='files/', verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'história', 'verbose_name_plural': 'histórias'},
        ),
    ]
