# Generated by Django 5.2 on 2025-06-02 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0014_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'sobre', 'verbose_name_plural': 'sobre'},
        ),
        migrations.AlterModelOptions(
            name='directors',
            options={'verbose_name': 'diretoria', 'verbose_name_plural': 'diretoria'},
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name': 'história', 'verbose_name_plural': 'história'},
        ),
        migrations.CreateModel(
            name='Comment_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome')),
                ('comment', models.TextField(max_length=250, verbose_name='Deixe seu comentário')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='aprepi.recent_news')),
            ],
            options={
                'verbose_name': 'comentário',
                'verbose_name_plural': 'comentários',
            },
        ),
    ]
