# Generated by Django 5.2 on 2025-06-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0016_reply_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('file', models.FileField(upload_to='atas/', verbose_name='Arquivo da ata')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
            ],
            options={
                'verbose_name': 'ata',
                'verbose_name_plural': 'atas',
            },
        ),
    ]
