# Generated by Django 5.2 on 2025-06-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0018_eventimage_eventvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventimage',
            options={'verbose_name': 'imagem de evento', 'verbose_name_plural': 'imagens de eventos'},
        ),
        migrations.AlterModelOptions(
            name='eventvideo',
            options={'verbose_name': 'vídeo de evento', 'verbose_name_plural': 'vídeos de eventos'},
        ),
    ]
