# Generated by Django 5.2 on 2025-06-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0019_alter_eventimage_options_alter_eventvideo_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventvideo',
            name='thumbnail',
            field=models.ImageField(upload_to='event_thumbs/', verbose_name='Escolha uma miniatura'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='video',
            field=models.FileField(upload_to='event_video', verbose_name='Escolha um vídeio'),
        ),
    ]
