# Generated by Django 5.2.6 on 2025-10-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0020_alter_eventvideo_thumbnail_alter_eventvideo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_users',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Gênero'),
        ),
    ]
