# Generated by Django 5.2.6 on 2025-10-31 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0022_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('image', models.ImageField(blank=True, null=True, upload_to='contribute/', verbose_name='Imagem')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'contribua',
                'verbose_name_plural': 'contribua',
            },
        ),
    ]
