# Generated by Django 5.2.6 on 2025-10-31 15:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0023_contribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribute',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
