# Generated by Django 5.2.6 on 2025-11-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aprepi', '0024_alter_contribute_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('image1', models.ImageField(upload_to='carroussel/', verbose_name='Imagem 1')),
                ('image2', models.ImageField(upload_to='carroussel/', verbose_name='Imagem 2')),
                ('image3', models.ImageField(upload_to='carroussel/', verbose_name='Imagem 3')),
            ],
            options={
                'verbose_name': 'carrossel',
                'verbose_name_plural': 'carrosseis',
            },
        ),
    ]
